spring.application.name=Security

server.port= 8081

# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/post

# Database credentials
spring.datasource.username=postgres
spring.datasource.password=root

## JDBC Driver
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## Hibernate settings
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#
## Show SQL queries (optional)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


##Secutiy config that is
#spring.security.user.name = Pankaj
#spring.security.user.password = Pankaj@11
